baseURL = "/"
languageCode = "ru"
title = "Hugo Site"

[taxonomies]
    tag = "tags"
    catagogory = "categories"
    mood = "moods"

[[menu.main]]
    name = "Продукты"
    title = "Products"
    url  = "/products/"
    weight = 1

[[menu.main]]
    name = "Доставка"
    title = "Delivery"
    url  = "/delivery/"
    weight = 2

[[menu.main]]
    name = "Контакты"
    title = "Contacts"
    url = "/contacts/"
    weight = 3